### PR TITLE
sticky top bar when scrolling

### PR DESCRIPTION
**Pull request by Robinhoets**
Files changed:
- base.html
- style.css

What:
- Header sticks to top of page when scrolling

How:
- js script in base
- sticky css

### CODE REVIEW

**Comment by GongBingWong** [comment]
Is this meant to happen?
image
image

**Comment by Robinhoets** [comment]
@GongBingWong I fixed the overlay issue. Try it now.

**Comment by GongBingWong** [comment]
I committed a fix to the header snapping bug (where scrolling up to the top skips the headings and immediately snaps up to the top). Maybe should have named commit "Fix heading snapping bug" since "header" and "heading" are different.

**Comment by Robinhoets** [comment]
@GongBingWong I pulled and it looks good to commit for me.

**Review by GongBingWong — APPROVED** [review]

**Pull request merged**
